name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build api
      run: go mod tidy; go build -o skill-icons main.go

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./skill-icons
        user_name: ${{ github.actor }}
        user_email: ${{ github.actor }}@users.noreply.github.com
